const detailedKana0 = {
    A: {

    }
}

const detailedKana = [
    { h: 'あ', k: '', r: 'A', u: '', hiragana: true, type: 'kana' },
    { h: 'い', k: '', r: 'I', u: '', hiragana: true, type: 'kana' },
    { h: 'う', k: '', r: 'U', u: '', hiragana: true, type: 'kana' },
    { h: 'え', k: '', r: 'E', u: '', hiragana: true, type: 'kana' },
    { h: 'お', k: '', r: 'O', u: '', hiragana: true, type: 'kana' },
    { h: 'か', k: '', r: 'KA', u: '', hiragana: true, type: 'kana' },
    { h: 'き', k: '', r: 'KI', u: '', hiragana: true, type: 'kana' },
    { h: 'く', k: '', r: 'KU', u: '', hiragana: true, type: 'kana' },
    { h: 'け', k: '', r: 'KE', u: '', hiragana: true, type: 'kana' },
    { h: 'こ', k: '', r: 'KO', u: '', hiragana: true, type: 'kana' },
    { h: 'が', k: '', r: 'GA', u: '', hiragana: true, type: 'kana' },
    { h: 'ぎ', k: '', r: 'GI', u: '', hiragana: true, type: 'kana' },
    { h: 'ぐ', k: '', r: 'GU', u: '', hiragana: true, type: 'kana' },
    { h: 'げ', k: '', r: 'GE', u: '', hiragana: true, type: 'kana' },
    { h: 'ご', k: '', r: 'GO', u: '', hiragana: true, type: 'kana' },
    { h: 'さ', k: '', r: 'SA', u: '', hiragana: true, type: 'kana' },
    { h: 'し', k: '', r: 'SHI', u: '', hiragana: true, type: 'kana' },
    { h: 'す', k: '', r: 'SU', u: '', hiragana: true, type: 'kana' },
    { h: 'せ', k: '', r: 'SE', u: '', hiragana: true, type: 'kana' },
    { h: 'そ', k: '', r: 'SO', u: '', hiragana: true, type: 'kana' },
    { h: 'ざ', k: '', r: 'ZA', u: '', hiragana: true, type: 'kana' },
    { h: 'じ', k: '', r: 'JI', u: '', hiragana: true, type: 'kana' },
    { h: 'ず', k: '', r: 'ZU', u: '', hiragana: true, type: 'kana' },
    { h: 'ぜ', k: '', r: 'ZE', u: '', hiragana: true, type: 'kana' },
    { h: 'ぞ', k: '', r: 'ZO', u: '', hiragana: true, type: 'kana' },
    { h: 'た', k: '', r: 'TA', u: '', hiragana: true, type: 'kana' },
    { h: 'ち', k: '', r: 'CHI', u: '', hiragana: true, type: 'kana' },
    { h: 'つ', k: '', r: 'TSU', u: '', hiragana: true, type: 'kana' },
    { h: 'て', k: '', r: 'TE', u: '', hiragana: true, type: 'kana' },
    { h: 'と', k: '', r: 'TO', u: '', hiragana: true, type: 'kana' },
    { h: 'だ', k: '', r: 'DA', u: '', hiragana: true, type: 'kana' },
    { h: 'ぢ', k: '', r: 'JI', u: '', hiragana: true, type: 'kana' },
    { h: 'づ', k: '', r: 'ZU', u: '', hiragana: true, type: 'kana' },
    { h: 'で', k: '', r: 'DE', u: '', hiragana: true, type: 'kana' },
    { h: 'ど', k: '', r: 'DO', u: '', hiragana: true, type: 'kana' },
    { h: 'な', k: '', r: 'NA', u: '', hiragana: true, type: 'kana' },
    { h: 'に', k: '', r: 'NI', u: '', hiragana: true, type: 'kana' },
    { h: 'ぬ', k: '', r: 'NU', u: '', hiragana: true, type: 'kana' },
    { h: 'ね', k: '', r: 'NE', u: '', hiragana: true, type: 'kana' },
    { h: 'の', k: '', r: 'NO', u: '', hiragana: true, type: 'kana' },
    { h: 'は', k: '', r: 'HA', u: '', hiragana: true, type: 'kana' },
    { h: 'ひ', k: '', r: 'HI', u: '', hiragana: true, type: 'kana' },
    { h: 'ふ', k: '', r: 'FU', u: '', hiragana: true, type: 'kana' },
    { h: 'へ', k: '', r: 'HE', u: '', hiragana: true, type: 'kana' },
    { h: 'ほ', k: '', r: 'HO', u: '', hiragana: true, type: 'kana' },
    { h: 'ぱ', k: '', r: 'PA', u: '', hiragana: true, type: 'kana' },
    { h: 'ぴ', k: '', r: 'PI', u: '', hiragana: true, type: 'kana' },
    { h: 'ぷ', k: '', r: 'PU', u: '', hiragana: true, type: 'kana' },
    { h: 'ぺ', k: '', r: 'PE', u: '', hiragana: true, type: 'kana' },
    { h: 'ぽ', k: '', r: 'PO', u: '', hiragana: true, type: 'kana' },
    { h: 'ば', k: '', r: 'BA', u: '', hiragana: true, type: 'kana' },
    { h: 'び', k: '', r: 'BI', u: '', hiragana: true, type: 'kana' },
    { h: 'ぶ', k: '', r: 'BU', u: '', hiragana: true, type: 'kana' },
    { h: 'べ', k: '', r: 'BE', u: '', hiragana: true, type: 'kana' },
    { h: 'ぼ', k: '', r: 'BO', u: '', hiragana: true, type: 'kana' },
    { h: 'ま', k: '', r: 'MA', u: '', hiragana: true, type: 'kana' },
    { h: 'み', k: '', r: 'MI', u: '', hiragana: true, type: 'kana' },
    { h: 'む', k: '', r: 'MU', u: '', hiragana: true, type: 'kana' },
    { h: 'め', k: '', r: 'ME', u: '', hiragana: true, type: 'kana' },
    { h: 'も', k: '', r: 'MO', u: '', hiragana: true, type: 'kana' },
    { h: 'や', k: '', r: 'YA', u: '', hiragana: true, type: 'kana' },
    { h: 'ゆ', k: '', r: 'YU', u: '', hiragana: true, type: 'kana' },
    { h: 'よ', k: '', r: 'YO', u: '', hiragana: true, type: 'kana' },
    { h: 'ゃ', k: '', r: 'yA', u: '', hiragana: true, type: 'kana' },
    { h: 'ゅ', k: '', r: 'yU', u: '', hiragana: true, type: 'kana' },
    { h: 'ょ', k: '', r: 'yO', u: '', hiragana: true, type: 'kana' },
    { h: 'ら', k: '', r: 'RA', u: '', hiragana: true, type: 'kana' },
    { h: 'り', k: '', r: 'PI', u: '', hiragana: true, type: 'kana' },
    { h: 'る', k: '', r: 'RU', u: '', hiragana: true, type: 'kana' },
    { h: 'れ', k: '', r: 'RE', u: '', hiragana: true, type: 'kana' },
    { h: 'ろ', k: '', r: 'RO', u: '', hiragana: true, type: 'kana' },
	{ h: 'わ', k: '', r: 'WA', u: '', hiragana: true, type: 'kana' },
    { h: 'を', k: '', r: '*O', u: '', hiragana: true, type: 'kana' },
    { h: 'ん', k: '', r: 'N', u: '', hiragana: true, type: 'kana' },
    { h: 'っ', k: '', r: 'tu', u: '', hiragana: true, type: 'kana' },
]